<a href="https://colab.research.google.com/github/MINIVO2/Introduction_to_NLP/blob/main/08__introduction__to__NLP__in__tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#introduction to NLP Fundamentals in tensorflow

also known as sequence to sequence problem

##Get Helper Functions

In [ ]:
pip install tf_keras

In [ ]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

--2025-03-27 10:28:34--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2025-03-27 10:28:34 (73.0 MB/s) - ‘helper_functions.py’ saved [10246/10246]



In [ ]:
from helper_functions import unzip_data,walk_through_dir, create_tensorboard_callback, plot_loss_curves, compare_historys

##Get a text dataset
 we are using kaggles introduction to NLP dataset

 https://www.kaggle.com/competitions/nlp-getting-started

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip#mean time i have got the resource from mrdbourke github

--2025-03-27 10:28:42--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.197.207, 74.125.135.207, 74.125.142.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.197.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.01s   

2025-03-27 10:28:42 (58.5 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]

--2025-03-27 10:28:42--  http://time/
Resolving time (time)... failed: Name or service not known.
wget: unable to resolve host address ‘time’
--2025-03-27 10:28:42--  http://i/
Resolving i (i)... failed: Name or service not known.
wget: unable to resolve host address ‘i’
--2025-03-27 10:28:42--  http://have/
Resolving have (have)... failed: Name or service not known.
wget: unable to resolve host address ‘

In [ ]:
#unzip the data

unzip_data("/content/nlp_getting_started.zip")



##Become one with the data

In [ ]:
import pandas as pd

test_data = pd.read_csv("/content/test.csv")
train_data = pd.read_csv("/content/train.csv")



In [ ]:
#print(test_data.to_string())

In [ ]:
pd.DataFrame(test_data)
train_data.head()


id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
train_data["text"][0]

'Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'

###Shuffle the present data using pandas methods sample

In [ ]:
train_data_shuffled = train_data.sample(frac = 1, random_state = 42) #frac 1 means 100% of the data, we can o.1 as 10% of the data
train_data_shuffled

id       keyword                        location  \
2644   3796   destruction                             NaN   
2227   3185        deluge                             NaN   
5448   7769        police                              UK   
132     191    aftershock                             NaN   
6845   9810        trauma           Montgomery County, MD   
...     ...           ...                             ...   
5226   7470  obliteration                         Merica!   
5390   7691         panic                             NaN   
860    1242         blood                             NaN   
7603  10862           NaN                             NaN   
7270  10409     whirlwind  Stamford & Cork (& Shropshire)   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0  
...                                                 ...     ...  
5226  @Eganator2000 There aren't many Obliteration s...       0  
5390  just had a panic attack bc I don't have enough...       0  
860   Omron HEM-712C Automatic Blood Pressure Monito...       0  
7603  Officials say a quarantine is in place at an A...       1  
7270  I moved to England five years ago today. What ...       1  

[7613 rows x 5 columns]

In [ ]:
test_data.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
train_data.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [ ]:
#total number of samples

len(train_data), len(test_data)

(7613, 3263)

###visualize some training data

In [ ]:
#generate random samples

import random
random_index = random.randint(0, len(train_data)-5) #create random samples not higher than the training data
for row in train_data_shuffled[["text", "target"]][random_index: random_index+5].itertuples(): # https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html
  _, text, target = row

  print(f"Target: {target}", "(fake news)" if target > 0 else "(Not fake news)")
  print(f"Text: \n {text} \n")
  print("____ \n")

Target: 0 (Not fake news)
Text: 
 Beyonce Is my pick for http://t.co/nnMQlz91o9 Fan Army #Beyhive http://t.co/o91f3cYy0R 78 

____ 

Target: 1 (fake news)
Text: 
 Learn how to evacuate your home in the event of a #wildfire view videos at http://t.co/bGeRLjamTE #CA #NV #UT #CO #OR http://t.co/sPuHuvgAsy 

____ 

Target: 1 (fake news)
Text: 
 #vaxshill 2 deaths from measles complications in 10 yrs everyone looses their shit. 8 dead from Legionnaires in a month &amp; crickets 

____ 

Target: 1 (fake news)
Text: 
 Summer heat drives bobcats to Calgary backyards ~ 3 http://t.co/kEstuUYc4t http://t.co/PzFBb1P1mj 

____ 

Target: 1 (fake news)
Text: 
 My baby girls car wreak this afternoon thank God no serious injuries and she was wearing her seatbelt!!!... http://t.co/NJQV45ndS2 

____ 



###split the data into training and validation sets

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#Split training data into train_data and validation data
val_sentences, train_sentences, val_labels, train_labels = train_test_split(train_data_shuffled["text"].to_numpy(),
                                                                             train_data_shuffled["target"].to_numpy(),
                                                                             train_size = 0.5, #use 10% of the data
                                                                             random_state = 42)


In [ ]:
train_labels


array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(3807, 3807, 3806, 3806)

In [ ]:
#check the first 10 samples
train_sentences[:10], train_labels[:10]

(array(['DFR EP016 Monthly Meltdown - On Dnbheaven 2015.08.06 http://t.co/EjKRf8N8A8 #Drum and Bass #heavy #nasty http://t.co/SPHWE6wFI5',
        'FedEx no longer to transport bioterror germs in wake of anthrax lab mishaps http://t.co/qZQc8WWwcN via @usatoday',
        'Gunmen kill four in El Salvador bus attack: Suspected Salvadoran gang members killed four people and wounded s... http://t.co/CNtwB6ScZj',
        '@camilacabello97 Internally and externally screaming',
        'Radiation emergency #preparedness starts with knowing to: get inside stay inside and stay tuned http://t.co/RFFPqBAz2F via @CDCgov',
        'Investigators rule catastrophic structural failure resulted in 2014 Virg.. Related Articles: http://t.co/Cy1LFeNyV8',
        'How the West was burned: Thousands of wildfires ablaze in #California alone http://t.co/iCSjGZ9tE1 #climate #energy http://t.co/9FxmN0l0Bd',
        "Map: Typhoon Soudelor's predicted path as it approaches Taiwan; expected to make landfall over so

##Converting text into numbers

there are two methods:-
1. Tokenization
2. Embedding

###Text Vectorization(tokenization)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

#use the default TextVectorization parameters

text_vectorizer = TextVectorization(max_tokens = None, #how many words in the vocabulary, none means it will automate according to data(automatically add <00V>)
                                    standardize = "lower_and_strip_punctuation",
                                    split = "whitespace", #white spaces between the sample
                                    ngrams = None, # create a group of n-words eg: 2 words as 1 ngram
                                    output_mode = 'int',#how to map tokens to numbers
                                    output_sequence_length = None, #how long do you want your sentences to be
                                    pad_to_max_tokens = False # if you want to pad then set max_tokens to a value
                                    )

In [ ]:
len(train_sentences[0].split())

15

In [ ]:
round(sum([len(i.split()) for i in train_sentences]))

56821

In [ ]:
#average number of tokens in training tweets
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

15

In [ ]:
# re-setup textvectorization variables
max_vocabulary_length = 10000 #max number of words to have in our vocabulary
max_length = 15 #max length our sentences can be




In [ ]:
text_vectorizer = TextVectorization(max_tokens = max_vocabulary_length,
                                    output_mode = "int",
                                    output_sequence_length = max_length
                                    )

###text_vectorizer.adapt()

In [ ]:
#fit the text vectorizer to the training text
text_vectorizer.adapt(train_sentences )

In [ ]:
#create a sample sentence and tokenize it

sample_sentence = "Theres a flood in my street! "
text_vectorizer([sample_sentence]) #text_vectorizer accepts as a list



<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[489,   3, 199,   4,  13, 655,   0,   0,   0,   0,   0,   0,   0,
          0,   0]])>

the length is 6 for above code so the others is 0 which shows the need of output_sequence_length = 15

In [ ]:
random_sentence = random.choice(train_sentences)
print(f"Original Sentences : \n{random_sentence} \n\n Vectorized sentence : ")
text_vectorizer([random_sentence])

Original Sentences : 
@BroseidonRex @dapurplesharpie I skimmed through twitter and missed this body bagging. 

 Vectorized sentence : 


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[   1,    1,    7, 5656,  286,  300,    8, 2368,   19,   92,  701,
           0,    0,    0,    0]])>

###text_vectorizer.get_vocabulary()

In [ ]:
#Get the Unique words in the vocabulary

words_in_vocab = text_vectorizer.get_vocabulary()# get all the unique words in our training words
top_5_words= words_in_vocab[:5] #first 5
less_5_words = words_in_vocab[-5:] #last 5

top_5_words, less_5_words

(['', '[UNK]', np.str_('the'), np.str_('a'), np.str_('in')],
 [np.str_('httptcocnqae9foj6'),
  np.str_('httptcocmweiojj55'),
  np.str_('httptcocmsgexm4fc'),
  np.str_('httptcocm8uni1mrg'),
  np.str_('httptcoclyj32l333')])

# Create an Emmbedding layer

The parameters we care most about for our embedding layer:

input_dim = the size of our vocabulary


output_dim = the size of the embedding vector, for eg:- a value of 100 would mean each token gets represented by a vector 100 long.

input_length = length of the sequence being passed to the embedding layer

https://www.tensorflow.org/text/guide/word_embeddings






In [ ]:
from tensorflow.keras.layers import Embedding

embedding = Embedding(input_dim = max_vocabulary_length, #set input shape
                      output_dim = 128, #divisible by 8
                      embeddings_initializer = "uniform",#default value
                      input_length = max_length) #how long is each input

embedding


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


<Embedding name=embedding_2, built=False>

In [ ]:
#get a random sentence on the training set
random_sentence = random.choice(train_sentences)

print(f"original sentences : {random_sentence} \n \n Embedded version :"
      )

#get the random sentence into embedded version(turns positive integers (indexes) into dense vectors of fixed size.)
embeded_sample = embedding(text_vectorizer([random_sentence])) #in text_vectorizer the sentence should go as a list

embeded_sample


original sentences : #TBT Remember that time Patrick Kane attacked a cab driver over .20 
 
 Embedded version :


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[-0.0088719 , -0.03012196,  0.04989265, ..., -0.00903078,
         -0.02876428, -0.04797833],
        [-0.04701139, -0.03343867,  0.01413875, ...,  0.03827201,
          0.02835629, -0.04519594],
        [ 0.04728333, -0.03747705, -0.02219138, ...,  0.02632814,
         -0.04876266, -0.0344279 ],
        ...,
        [ 0.02404917, -0.01206158, -0.00340217, ...,  0.02877803,
          0.00255629,  0.01426164],
        [ 0.02404917, -0.01206158, -0.00340217, ...,  0.02877803,
          0.00255629,  0.01426164],
        [ 0.02404917, -0.01206158, -0.00340217, ...,  0.02877803,
          0.00255629,  0.01426164]]], dtype=float32)>

In [ ]:
embeded_sample[0][0] , embeded_sample[0][0].shape, random_sentence[0]

(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([-0.0088719 , -0.03012196,  0.04989265, -0.01615018,  0.00524261,
        -0.04142929,  0.03234838,  0.01403276, -0.02436771, -0.03298137,
        -0.01794798, -0.00205457, -0.02991276,  0.04946334, -0.04346695,
        -0.02424481, -0.04522957,  0.02825779, -0.02748313, -0.04366148,
         0.03772565,  0.01202076, -0.04064751, -0.04672204, -0.04183923,
        -0.00010184, -0.04221885, -0.02555157, -0.03920915, -0.02310388,
        -0.04714621, -0.01757823,  0.04947406, -0.04180498,  0.0050538 ,
        -0.02233582,  0.0141587 ,  0.02638016,  0.02601904, -0.01786359,
        -0.00070983, -0.04313129,  0.00191562, -0.00364534, -0.04188645,
         0.01031489, -0.00226891,  0.04679792,  0.01827185, -0.0139251 ,
        -0.00698122, -0.00143267,  0.0307428 ,  0.04993891, -0.02108172,
        -0.04097167, -0.02448876,  0.03294721, -0.02770618, -0.03953445,
        -0.01111694,  0.00043485, -0.00289344,  0.02116934, -0.04969947,
  

##Modelling a text data set(running a series of experiments)

Scikit-learn machine learning map


##Model 0 : naive bayes (baseline)

https://github.com/arseniyturin/nlp_multinomial_naive_bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB # classifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

model_0 = Pipeline([
    ("Tfidf", TfidfVectorizer()),
    ("clf", MultinomialNB())# clf means classifier
])

model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('Tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
### evaluate our baseline model_0
baseline_score = model_0.score(val_sentences, val_labels)
baseline_score

print(f"it attend an accuracy of {baseline_score *100:.2f}%")

it attend an accuracy of 79.19%


In [ ]:
train_data.target.value_counts() #it is a 60 - 40 split nearly so the guessing might be at 55%

target
0    4342
1    3271
Name: count, dtype: int64

In [ ]:
#make predictions
baseline_preds = model_0.predict(val_sentences)
baseline_preds[:10]

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
val_sentences[:10]

array(['#?? #?? #??? #??? Suicide bomber kills 15 in Saudi security site mosque - Reuters  http://t.co/LgpNe5HkaO',
       'Sitting around a fire sounds great right about now',
       'Deputies: Dog dispute leads to fatal shooting in Person County http://t.co/OazgHoZGYa #gunfail #nra',
       'What really happened in the Taken King Story Trailer. A space battle that ripped a hole in Saturn. @EyTay @neur0sis http://t.co/ZYRZX6dfki',
       '.@KurtSchlichter Yep considering that *millions* of Japanese fatalities were projected for Downfall. @_FreeMarketeer @dibang',
       'and he almost collapsed bc he said his wish came true moderately FUCK',
       "@AaronTheFM guys to scared to show his real name anyway he knows I'll bomb him",
       'New RAN report from the frontlines of human rights abuses and forest destruction for fashion.: http://t.co/tYDXauuEnQ',
       'That sounds about right. Our building will have a thunderstorm inside one day when the air masses collide. https://t.co/2rTQ

### creating and evaluation function for our model experiments
compare our models predictions with truth labels using following metrics

accuracy

precesion recall

f1-score

confusion matrix

https://scikit-learn.org/stable/modules/model_evaluation.html

###calculate_results()

In [ ]:
# Function to evalaute: accuracy, precision, recall, F1-score
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results_advanced(y_true, y_pred):
  """
  Calculates model accuracy, precision, recall and f1 score of a binary classification model.

  Args:
  ----
  y_true = true labels in the form of a 1D array
  y_pred = predicted label in the form of a 1D array

  Returns a dictionary of accuracy, precision, recall and f1-score between y_true and y_pred.
  """
  # Calculate model accuracy
  model_accuracy = accuracy_score(y_true, y_pred) * 100 # get accuracy score in percentage value
  # Calculate model precision, recall and f1 score using "weighted" avergage
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted") #'_' cause we dont wanty support, it acts like a blank
  # Create a dictionary of model results
  model_results = {"accuracy": model_accuracy,
                   "precision": model_precision,
                   "recall": model_recall,
                   "f1": model_f1}
  return model_results




In [ ]:
#function to evaluate: accuracy, precesion, recall, f1_score

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

def calculate_results(test_labels, predictions): #y_true = test_labels, y_pred = predictions made by the model

  '''
  calculates models accuracy, precesion, recall, and F1-score of a binary classification

  '''

  #finding the accuracy score
  accuracy = accuracy_score(test_labels, predictions)

  #finding precesion score
  precision = precision_score(test_labels, predictions)

  #finding the recall_score
  recall = recall_score(test_labels, predictions)

  #finding the f1-score
  f1score = f1_score(test_labels, predictions)


  print(f"The accuracy score is {accuracy *100:.2f}")
  print(f"The precesion score is {precision *100:.2f}")
  print(f"The recall score is {recall *100:.2f}")
  print(f"The f1_score is {f1score *100:.2f}")

In [ ]:
calculate_results(val_labels, baseline_preds)

The accuracy score is 79.19
The precesion score is 84.03
The recall score is 62.08
The f1_score is 71.41


In [ ]:
baseline_results =calculate_results_advanced(val_labels, baseline_preds)
baseline_results

{'accuracy': 79.1907514450867,
 'precision': 0.7995604528658318,
 'recall': 0.791907514450867,
 'f1': 0.7852209208324513}

##Model1 : A simple Dense model

In [ ]:
from helper_functions import create_tensorboard_callback


#create a directory to save tensorboard logs

SAVE_DIR = "model_logs"

In [ ]:
#Build model with the functional API
from tensorflow.keras import layers

input = layers.Input(shape = (1,), dtype = tf.string) #inputs are oone_directional as binary classification
x= text_vectorizer(input) #turn the input text into numbers
x = embedding(x) #create an embedding of numberised input
x = layers.GlobalAveragePooling1D()(x) #condense the feature vetor for each token to one vector
#x = layers.GlobalMaxPool1D()(x)
output = layers.Dense(1, activation = "sigmoid")(x) #as it is a binary classification
model_1 = tf.keras.Model(input, output, name= "model_1_dense")

In [ ]:
model_1.summary()

Model: "model_1_dense"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 1)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ text_vectorization_5                 │ (None, 15)                  │               0 │
│ (TextVectorization)                  │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding_2 (Embedding)              │ (None, 15, 128)             │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_average_pooling1d             │ (None, 128)                 │               0 │
│ (GlobalAveragePooling1D)             │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,280,129 (4.88 MB)

 Trainable params: 1,280,129 (4.88 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#compile the model

model_1.compile(
    loss = "binary_crossentropy",
    optimizer = tf.keras.optimizers.Adam(),
    metrics = ["accuracy"]
)


In [ ]:
#fit the model
model_1_history = model_1.fit(train_sentences,
                              train_labels,
                              epochs = 5,
                              validation_data = (val_sentences, val_labels), # as a tuple
                              callbacks = [create_tensorboard_callback(dir_name= SAVE_DIR,
                                                                       experiment_name = "model_1_dense")]) # as a list

Saving TensorBoard log files to: model_logs/model_1_dense/20250327-105906
Epoch 1/5
119/119 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.6062 - loss: 0.6710 - val_accuracy: 0.6968 - val_loss: 0.5992
Epoch 2/5
119/119 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.7712 - loss: 0.5531 - val_accuracy: 0.7672 - val_loss: 0.5118
Epoch 3/5
119/119 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.8335 - loss: 0.4238 - val_accuracy: 0.7914 - val_loss: 0.4758
Epoch 4/5
119/119 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - accuracy: 0.8769 - loss: 0.3293 - val_accuracy: 0.7924 - val_loss: 0.4665
Epoch 5/5
119/119 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.9054 - loss: 0.2697 - val_accuracy: 0.7901 - val_loss: 0.4689


In [ ]:
# evaluate the model

model_1.evaluate(val_sentences, val_labels)

119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7826 - loss: 0.4767


[0.4688521921634674, 0.7900683283805847]

In [ ]:
model_1_predict = model_1.predict(val_sentences)
model_1_predict[0]

119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


array([0.99076897], dtype=float32)

In [ ]:
model_1_predict.shape #It is giving output for each token ie, 15 tokens
                      #hence it should be (761,1) as output layer has 1 output layer
                      # it is giving 1 prediction probability per sample
                      # its creating output layer per token

                      #apply GlobalAveragePooling1d to change 128 per token to whole thing as 128

(3806, 1)

In [ ]:
model_1_predict = tf.squeeze(tf.round(model_1_predict)) #to remove '1' dimension from (761,1) use squeeze
model_1_predict[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 0., 1., 0., 1., 0., 0., 0., 1., 0.], dtype=float32)>

In [ ]:
#calculate our results

model_1_results = calculate_results_advanced(val_labels, model_1_predict )
model_1_results

{'accuracy': 79.00683131897004,
 'precision': 0.790606221110691,
 'recall': 0.7900683131897005,
 'f1': 0.7867599623625295}

In [ ]:
sample_sentence = "what the hell is going on !!!!!!!"
text_vect = text_vectorizer([sample_sentence])




In [ ]:
def predict_tweet(tweet, model, text_vectorizer):
    # Ensure the tweet is a list of a single string
    tweet_vectorized = text_vectorizer([tweet])  # Correct input shape (1D list)

    # Get the model prediction
    prediction = model.predict(tweet_vectorized)

    # Extract confidence score
    confidence = round(float(prediction[0][0]) * 100, 2)

    # Interpret the result
    if prediction >= 0.5:
        print(f"🔴 Fake Tweet (Confidence: {confidence}%)")
    else:
        print(f"✅ Real Tweet (Confidence: {100 - confidence}%)")

In [ ]:
predict_tweet(text_vect, model_1)

TypeError: predict_tweet() missing 1 required positional argument: 'text_vectorizer'

In [ ]:
baseline_results

{'accuracy': 79.1907514450867,
 'precision': 0.7995604528658318,
 'recall': 0.791907514450867,
 'f1': 0.7852209208324513}

###compare two models


In [ ]:
import numpy as np

np.array(list(model_1_results.values())) > np.array(list(baseline_results.values()))

array([ True, False,  True,  True])

#Visualizing Learned Embeddings

In [ ]:
#Get the vocabulary from text vectorization layers

words_in_vocab = text_vectorizer.get_vocabulary()

len(words_in_vocab)

10000

In [ ]:
model_1.summary()

Model: "model_1_dense"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 1)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ text_vectorization_1                 │ (None, 15)                  │               0 │
│ (TextVectorization)                  │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding (Embedding)                │ (None, 15, 128)             │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_average_pooling1d             │ (None, 128)                 │               0 │
│ (GlobalAveragePooling1D)             │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,840,389 (14.65 MB)

 Trainable params: 1,280,129 (4.88 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,560,260 (9.77 MB)

In [ ]:
# Get the weight matrix of embedding layer
#(these are the numerical representation of each token in our training data)
embed_weights = model_1.get_layer("embedding").get_weights()[0]

embed_weights.shape #xame size as vocab and embedding dim

(10000, 128)

###create embedding file (we got from tensorflow's word embedding documentation)

https://www.tensorflow.org/text/guide/word_embeddings

embedding projection tool

https://projector.tensorflow.org/

In [ ]:
import io

out_v = io.open('vectors.tsv', 'w', encoding='utf-8')
out_m = io.open('metadata.tsv', 'w', encoding='utf-8')

for index, word in enumerate(words_in_vocab):
  if index == 0:
    continue  # skip 0, it's padding.
  vec = embed_weights[index]
  out_v.write('\t'.join([str(x) for x in vec]) + "\n")
  out_m.write(word + "\n")
out_v.close()
out_m.close()

In [ ]:
#download files to from colab to upload to projector
# try:
#   from google.colab import files
#   files.download('vectors.tsv')
#   files.download('metadata.tsv')
# except Exception:
#   pass

##Model 2: LSTM

In [ ]:
from tensorflow.keras import layers

inputs = layers.Input(shape=(1,), dtype = "string")
x = text_vectorizer(inputs)
x = embedding(x)
# print(x.shape)
# x= layers.LSTM(units = 64, return_sequences = True)(x) # when your stacking RNNs sequence together you need to return_sequences = TRUE
# print(x.shape)
x= layers.LSTM(64)(x)
# print(x.shape)
# x= layers.Dense(64, activation = 'relu')(x)
outputs= layers.Dense(1,activation = "sigmoid")(x)
model_2 = tf.keras.Model(inputs, outputs, name = "model_2_LSTM" )





In [ ]:
model_2.summary()

Model: "model_2_LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 1)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ text_vectorization_1                 │ (None, 15)                  │               0 │
│ (TextVectorization)                  │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding (Embedding)                │ (None, 15, 128)             │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 64)                  │          49,408 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,329,473 (5.07 MB)

 Trainable params: 1,329,473 (5.07 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#compile the model
model_2.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])

In [ ]:
#fit the model
model_2.fit(train_sentences,
            train_labels,
            epochs = 5,
            validation_data = (val_sentences, val_labels),
            callbacks = [create_tensorboard_callback(SAVE_DIR, "model_2_LSTM")])

Saving TensorBoard log files to: model_logs/model_2_LSTM/20240914-120340
Epoch 1/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 8s 25ms/step - accuracy: 0.9049 - loss: 0.2946 - val_accuracy: 0.7976 - val_loss: 0.5440
Epoch 2/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - accuracy: 0.9460 - loss: 0.1516 - val_accuracy: 0.7806 - val_loss: 0.6307
Epoch 3/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - accuracy: 0.9527 - loss: 0.1279 - val_accuracy: 0.7832 - val_loss: 0.7069
Epoch 4/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 10s 23ms/step - accuracy: 0.9625 - loss: 0.1049 - val_accuracy: 0.7714 - val_loss: 0.7903
Epoch 5/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - accuracy: 0.9684 - loss: 0.0838 - val_accuracy: 0.7648 - val_loss: 0.9411


In [ ]:
#Make predictions on LSTM Model
model_2_LSTM_preds = model_2.predict(val_sentences)
model_2_LSTM_preds[:10]

24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step


array([[1.4553422e-03],
       [7.4801631e-03],
       [9.9872345e-01],
       [9.9987471e-01],
       [6.5516960e-04],
       [5.2517251e-04],
       [9.9122059e-01],
       [9.9974138e-01],
       [2.1830652e-02],
       [5.6177708e-03]], dtype=float32)

In [ ]:
model_2_preds = tf.squeeze(tf.round(model_2_LSTM_preds))
model_2_preds

<tf.Tensor: shape=(761,), dtype=float32, numpy=
array([0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0

In [ ]:
val_labels

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,

In [ ]:
model_2_results = calculate_results_advanced(y_true = val_labels, y_pred = model_2_preds)
model_2_results

{'accuracy': 76.47831800262811,
 'precision': 0.762966884419267,
 'recall': 0.7647831800262812,
 'f1': 0.7631549805961875}

##Model 3 : GRU
Another popular and effective RNN component is the GRU or gated recurrent unit.


In [ ]:
from tensorflow.keras import layers

inputs = layers.Input(shape = (1,), dtype = "string")
x = text_vectorizer(inputs)
x= embedding(x)
# print(x.shape)
x = layers.GRU(units = 64, return_sequences = True )(x)  # when your stacking RNNs sequence together you need to return_sequences = TRUE
# print(x.shape)
x = layers.LSTM(42, return_sequences = True )(x)
# print(x.shape)
x = layers.GRU(99)(x)
print(x.shape)
x = layers.Dense(64,activation = 'relu')(x)
# print(x.shape)
# x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1,activation = 'sigmoid')(x)
model_3 = tf.keras.Model(inputs, outputs,name = "model_3_GRU" )

(None, 99)


In [ ]:
model_3.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])

model_3.fit(train_sentences,
            train_labels,
            epochs = 5,
            validation_data=(val_sentences,val_labels),
            callbacks = [create_tensorboard_callback(SAVE_DIR, "model_3_GRU")]
            )

Saving TensorBoard log files to: model_logs/model_3_GRU/20240914-120425
Epoch 1/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 20s 58ms/step - accuracy: 0.9356 - loss: 0.2237 - val_accuracy: 0.7674 - val_loss: 0.7736
Epoch 2/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9722 - loss: 0.0767 - val_accuracy: 0.7477 - val_loss: 1.2312
Epoch 3/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 20s 45ms/step - accuracy: 0.9728 - loss: 0.0561 - val_accuracy: 0.7503 - val_loss: 1.1733
Epoch 4/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9692 - loss: 0.0673 - val_accuracy: 0.7687 - val_loss: 1.3363
Epoch 5/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - accuracy: 0.9768 - loss: 0.0501 - val_accuracy: 0.7635 - val_loss: 1.5070


In [ ]:
model_3.summary()

Model: "model_3_GRU"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)           │ (None, 1)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ text_vectorization_1                 │ (None, 15)                  │               0 │
│ (TextVectorization)                  │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding (Embedding)                │ (None, 15, 128)             │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru (GRU)                            │ (None, 15, 64)              │          37,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 15, 42)              │          17,976 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru_1 (GRU)                          │ (None, 99)                  │          42,471 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 64)                  │           6,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,152,482 (15.84 MB)

 Trainable params: 1,384,160 (5.28 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,768,322 (10.56 MB)

In [ ]:
model_3_pred_GRU = model_3.predict(val_sentences)
model_3_pred_GRU[:10]

24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step


array([[5.8825117e-05],
       [4.1207131e-03],
       [9.9978071e-01],
       [9.9990278e-01],
       [3.0758340e-05],
       [1.2034756e-05],
       [9.9955952e-01],
       [9.9989343e-01],
       [3.6441477e-05],
       [4.4033168e-05]], dtype=float32)

In [ ]:
model_3_preds = tf.squeeze(tf.round(model_3_pred_GRU))
model_3_preds

<tf.Tensor: shape=(761,), dtype=float32, numpy=
array([0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1.,
       1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0

In [ ]:
model_3_results = calculate_results_advanced(y_true = val_labels, y_pred = model_3_preds)
model_3_results

{'accuracy': 76.34691195795007,
 'precision': 0.7614595973462698,
 'recall': 0.7634691195795007,
 'f1': 0.7612338443581166}

##Model 4 : Bidirectional Model

the representation(normally left to right) is done in both the ways (now both right to left and left to right)

In [ ]:
#Build a bidirectional Model

from tensorflow.keras import layers

inputs = layers.Input(shape= (1,), dtype = "string")
x= text_vectorizer(inputs)
x= embedding(x)
# x= layers.Bidirectional(layers.LSTM(64, return_sequences = True))(x)
# x= layers.Bidirectional(layers.GRU(64), return_sequences = True)(x)
x= layers.Bidirectional(layers.LSTM(64))(x)
# x= layers.Dense(64, activation = "relu")(x)
outputs= layers.Dense(1, activation = "sigmoid")(x)

model_4 = tf.keras.Model(inputs,outputs, name= "model_4_bidirectional")


In [ ]:
model_4.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])

model_4.fit(train_sentences,

            train_labels,
            epochs = 5,
            validation_data = (val_sentences, val_labels),
            callbacks = [create_tensorboard_callback(SAVE_DIR, "model_4_Bidirectional")]

)

Saving TensorBoard log files to: model_logs/model_4_Bidirectional/20240914-120547
Epoch 1/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 12s 33ms/step - accuracy: 0.9439 - loss: 0.1990 - val_accuracy: 0.7569 - val_loss: 0.9426
Epoch 2/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - accuracy: 0.9750 - loss: 0.0586 - val_accuracy: 0.7727 - val_loss: 1.3148
Epoch 3/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 9s 35ms/step - accuracy: 0.9780 - loss: 0.0461 - val_accuracy: 0.7438 - val_loss: 1.4464
Epoch 4/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 10s 32ms/step - accuracy: 0.9821 - loss: 0.0397 - val_accuracy: 0.7503 - val_loss: 1.4380
Epoch 5/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 10s 32ms/step - accuracy: 0.9806 - loss: 0.0409 - val_accuracy: 0.7569 - val_loss: 1.4497


In [ ]:
model_4_preds = model_4.predict(val_sentences)
model_4_preds

24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step


array([[6.22412073e-04],
       [2.78369822e-02],
       [9.99915361e-01],
       [9.99978602e-01],
       [8.32816440e-05],
       [3.26884983e-05],
       [9.99977350e-01],
       [9.99975622e-01],
       [3.97480530e-04],
       [1.63708557e-03],
       [4.44459292e-05],
       [1.19550336e-04],
       [3.58215779e-01],
       [7.48929456e-02],
       [7.26900876e-01],
       [3.51759970e-01],
       [2.27282697e-04],
       [1.70202315e-04],
       [1.26050282e-02],
       [5.22615016e-01],
       [3.13059002e-01],
       [1.29993277e-05],
       [3.75762224e-01],
       [9.99984205e-01],
       [2.89771031e-03],
       [9.99948263e-01],
       [3.06555897e-01],
       [9.38108133e-05],
       [2.64212402e-04],
       [2.41235476e-02],
       [2.38967172e-04],
       [1.93534695e-04],
       [8.27075215e-04],
       [1.62616387e-01],
       [3.84939939e-01],
       [2.63929274e-03],
       [5.93156099e-01],
       [2.80935565e-05],
       [9.99981642e-01],
       [1.51258113e-03],


In [ ]:
model_4_preds = tf.squeeze(tf.round(model_4_preds))
model_4_preds

<tf.Tensor: shape=(761,), dtype=float32, numpy=
array([0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1.,
       1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0

In [ ]:
model_4_results= calculate_results_advanced(y_true = val_labels, y_pred= model_4_preds)
model_4_results #worst results

{'accuracy': 75.68988173455979,
 'precision': 0.7550509487812761,
 'recall': 0.7568988173455979,
 'f1': 0.7553826953426793}

##convecutional neural network for Text(and other type of sequence)

for images its conv2d
for text  its conv1d

##Model 5: Conv1d model

In [ ]:
from tensorflow.keras import layers

text_sample = embedding(text_vectorizer(["this is a test sample"]))
conv_1d = layers.Conv1D(filters = 32, #32 filters traversing our text data
                        kernel_size = 5,#kernel size 5 means it looks at words at a time and as default stride is 1 so it steps 1 forward and get other 5 words
                        strides = 1,#stride = 1 it will slide over 1
                        padding = "valid", # default = 'valid , the output is smaller than input shape, but "same" the output is same shape as input
                        activation = "relu")  # padding "same" allows to put entire thing for learning the tokens creating extra layer around it

conv_1d_output = conv_1d(text_sample)
max_pool = layers.GlobalMaxPool1D()
max_pool_output = max_pool(conv_1d_output)

text_sample.shape, conv_1d_output.shape, max_pool_output.shape

(TensorShape([1, 15, 128]), TensorShape([1, 11, 32]), TensorShape([1, 32]))

In [ ]:
conv_1d_output

<tf.Tensor: shape=(1, 11, 32), dtype=float32, numpy=
array([[[0.        , 0.        , 0.        , 0.02943734, 0.00844424,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.0024293 , 0.00270947, 0.00245782, 0.        , 0.03677214,
         0.        , 0.09445505, 0.05589525, 0.06459787, 0.03778479,
         0.        , 0.        , 0.        , 0.        , 0.02130552,
         0.01669767, 0.        , 0.        , 0.03003175, 0.        ,
         0.00464008, 0.        ],
        [0.        , 0.00879888, 0.13682775, 0.0407259 , 0.03331727,
         0.0042131 , 0.        , 0.06853147, 0.06576467, 0.        ,
         0.        , 0.        , 0.00382771, 0.06349988, 0.04946678,
         0.        , 0.        , 0.05928758, 0.        , 0.        ,
         0.08159406, 0.        , 0.06106727, 0.        , 0.01550112,
         0.03627741, 0.04633816, 0.        , 0.02772658, 0.        ,
         0.        , 0.02484252],
        [0.        , 0.        , 0.08758123, 0.    

In [ ]:
max_pool_output

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[0.        , 0.05688243, 0.13682775, 0.0407259 , 0.08502268,
        0.0042131 , 0.01522255, 0.06853147, 0.09443679, 0.02834987,
        0.04229537, 0.01163952, 0.01223662, 0.11295874, 0.04946678,
        0.03708985, 0.09445505, 0.05928758, 0.06459787, 0.08306371,
        0.08159406, 0.05303787, 0.14012288, 0.        , 0.02130552,
        0.06325421, 0.04633816, 0.        , 0.06246358, 0.09774427,
        0.00464008, 0.02484252]], dtype=float32)>

In [ ]:
from tensorflow.keras import layers

# Assuming text_vectorizer converts the string to token indices (integer tensor)
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)  # Ensure this outputs integers
x = embedding(x)  # Embedding expects an integer input
x = layers.Conv1D(filters=64,
                  kernel_size=5,
                  padding="valid",
                  activation="relu")(x)
x = layers.GlobalMaxPool1D()(x)
output = layers.Dense(1, activation="sigmoid")(x)

model_5 = tf.keras.Model(inputs, output, name="model_5_Conv1D")

model_5.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

model_5.fit(train_sentences,
            train_labels,
            epochs=5,
            validation_data=(val_sentences, val_labels),
            callbacks=[create_tensorboard_callback(SAVE_DIR, "conv1D")])


Saving TensorBoard log files to: model_logs/conv1D/20240914-120639
Epoch 1/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 7s 23ms/step - accuracy: 0.9288 - loss: 0.1966 - val_accuracy: 0.7569 - val_loss: 0.8735
Epoch 2/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9727 - loss: 0.0785 - val_accuracy: 0.7424 - val_loss: 1.0032
Epoch 3/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9757 - loss: 0.0653 - val_accuracy: 0.7543 - val_loss: 1.1148
Epoch 4/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - accuracy: 0.9799 - loss: 0.0524 - val_accuracy: 0.7411 - val_loss: 1.1493
Epoch 5/5
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.9839 - loss: 0.0451 - val_accuracy: 0.7424 - val_loss: 1.1682


In [ ]:
model_5_preds = model_5.predict(val_sentences)
model_5_preds

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


array([[4.86394137e-01],
       [4.12409776e-04],
       [8.49825859e-01],
       [9.99996722e-01],
       [5.15495003e-07],
       [1.71597949e-05],
       [9.99992549e-01],
       [9.99999821e-01],
       [3.21094389e-03],
       [5.40407538e-01],
       [1.62740680e-03],
       [6.71721282e-05],
       [2.28437051e-01],
       [1.31084519e-02],
       [9.83732700e-01],
       [3.51333022e-01],
       [1.69933238e-03],
       [9.29464179e-04],
       [6.12474442e-01],
       [9.77162719e-01],
       [1.21197961e-01],
       [1.41772052e-08],
       [1.52774677e-01],
       [9.99797523e-01],
       [8.69333506e-01],
       [9.99992609e-01],
       [7.27832913e-01],
       [3.08499177e-04],
       [5.45367133e-03],
       [9.87405419e-01],
       [2.68606731e-04],
       [4.80280178e-05],
       [1.53510332e-01],
       [1.85924068e-01],
       [7.99236834e-01],
       [1.52209818e-01],
       [9.93316948e-01],
       [1.92550178e-05],
       [9.99999702e-01],
       [2.45455727e-02],


In [ ]:
model_5_preds = tf.squeeze(tf.round(model_5_preds))
model_5_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 1., 1., 0., 0., 1., 1., 0., 1.], dtype=float32)>

In [ ]:
calculate_results_advanced(y_true = val_labels, y_pred = model_5_preds)

{'accuracy': 74.24441524310119,
 'precision': 0.745717838988172,
 'recall': 0.7424441524310118,
 'f1': 0.7435675502540654}

In [ ]:
baseline_results

{'accuracy': 79.89487516425756,
 'precision': 0.8095562735335368,
 'recall': 0.7989487516425755,
 'f1': 0.7905183694503822}

##Model 6 : Tensorflow Hub Pretrained Sentence Encoder

we are using Universal Sentence Encoder
https://www.kaggle.com/models/google/universal-sentence-encoder

In [ ]:
sample_sentence

'Theres a flood in my street! '

In [ ]:
import tensorflow_hub as hub
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
embeddings = embed([
     sample_sentence,
    "when you can the universal sentence encoder on a sentences, it turns it into numbers"])

print(embeddings[0][:50])

tf.Tensor(
[-0.01157025  0.02485911  0.02878051 -0.012715    0.03971541  0.08827761
  0.02680988  0.05589838 -0.01068731 -0.00597293  0.00639321 -0.01819516
  0.00030816  0.09105889  0.05874645 -0.03180629  0.01512474 -0.05162925
  0.00991366 -0.06865345 -0.04209306  0.0267898   0.03011009  0.00321065
 -0.00337968 -0.04787356  0.0226672  -0.00985927 -0.04063615 -0.01292093
 -0.04666382  0.05630299 -0.03949255  0.00517682  0.02495827 -0.07014439
  0.0287151   0.0494768  -0.00633978 -0.08960193  0.02807119 -0.00808364
 -0.01360601  0.05998649 -0.10361788 -0.05195372  0.00232958 -0.02332531
 -0.03758106  0.03327729], shape=(50,), dtype=float32)


In [ ]:
embeddings[0].shape #512 dimensional vector

TensorShape([512])

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub

# Create a Keras layer using the Universal Sentence Encoder
sentence_encoder_layer = hub.KerasLayer(
    "https://tfhub.dev/google/universal-sentence-encoder/4",  # URL of the pre-trained model
    input_shape=[],        # Input shape is set to an empty list, meaning it accepts any input size
    dtype=tf.string,       # The input data type is a string (i.e., sentences)
    trainable=False,       # The layer is non-trainable, so the pre-trained weights will not be updated
    name="USE"             # Name of the layer
)


In [ ]:
#pip uninstall -y tensorflow tf-keras


In [ ]:

#pip install tensorflow==2.15

In [ ]:
import tf_keras
model_6 = tf_keras.Sequential([
    sentence_encoder_layer,
    tf_keras.layers.Dense(64, activation = "relu"),
    tf_keras.layers.Dense(1, activation = "sigmoid", name= "output_layer")
], name = "model_6_USE")

model_6.compile(loss = "binary_crossentropy",
                optimizer = tf_keras.optimizers.Adam(),
                metrics = ['accuracy'])
model_6.summary()

Model: "model_6_USE"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 USE (KerasLayer)            (None, 512)               256797824 
                                                                 
 dense (Dense)               (None, 64)                32832     
                                                                 
 output_layer (Dense)        (None, 1)                 65        
                                                                 
Total params: 256830721 (979.73 MB)
Trainable params: 32897 (128.50 KB)
Non-trainable params: 256797824 (979.61 MB)
_________________________________________________________________


In [ ]:
#pip install --upgrade tensorflow tensorflow-hub tensorboard


In [ ]:
model_6_history = model_6.fit(
    train_sentences,
    train_labels,
    epochs = 5,
    validation_data= (val_sentences, val_labels),

)

Epoch 1/5
215/215 [==============================] - 7s 15ms/step - loss: 0.5077 - accuracy: 0.7828 - val_loss: 0.4355 - val_accuracy: 0.7937
Epoch 2/5
215/215 [==============================] - 3s 12ms/step - loss: 0.4156 - accuracy: 0.8182 - val_loss: 0.4250 - val_accuracy: 0.8029
Epoch 3/5
215/215 [==============================] - 3s 13ms/step - loss: 0.4024 - accuracy: 0.8236 - val_loss: 0.4246 - val_accuracy: 0.8029
Epoch 4/5
215/215 [==============================] - 4s 19ms/step - loss: 0.3935 - accuracy: 0.8279 - val_loss: 0.4208 - val_accuracy: 0.8081
Epoch 5/5
215/215 [==============================] - 3s 12ms/step - loss: 0.3867 - accuracy: 0.8320 - val_loss: 0.4192 - val_accuracy: 0.8081


In [ ]:
model_6_preds = tf.squeeze(tf.round(model_6.predict(val_sentences)))
model_6_preds[:10]

24/24 [==============================] - 1s 10ms/step


<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 1., 1., 0., 1., 1., 1., 0., 0.], dtype=float32)>

In [ ]:
model_6_results = calculate_results_advanced(val_labels, model_6_preds)
model_6_results

{'accuracy': 80.81471747700394,
 'precision': 0.8070251260667504,
 'recall': 0.8081471747700394,
 'f1': 0.806885296163228}

In [ ]:
baseline_results

{'accuracy': 79.89487516425756,
 'precision': 0.8095562735335368,
 'recall': 0.7989487516425755,
 'f1': 0.7905183694503822}

#Model 7 : TF hub pretrained USE with 10 % data

transfer learning really helps when used on a smaller dataset, lets replicate'model_6' except we use 10% data

###create 10 % of the data

In [ ]:
train_10_percent = train_data_shuffled[["text", "target"]].sample(frac = 0.1, random_state = 42)

In [ ]:
#WARNING: Making data splits like below leads to data leakage
#DO NOT MAKE DATA SPLITS WHICH LEAK DATA FROM VALIDATION/ TEST SETS INTO TRAINING SETS
# train_sentences_10_percent = train_10_percent["text"].to_list()

# train_labels_10_percent = train_10_percent["target"].to_list()


In [ ]:
# fining the total number sentences/labels to be put into train sentences/labels

train_sen =int(0.1 * len(train_sentences))
train_lab = int(0.1* len(train_labels))

In [ ]:
train_sentences_10_percent = train_sentences[:train_sen]
train_labels_10_percent = train_labels[:train_lab]
train_labels[:10]

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
#check number of each label
pd.Series(np.array(train_labels_10_percent)).value_counts()

0    364
1    321
Name: count, dtype: int64

In [ ]:
train_10_percent["target"].value_counts() #not needed

target
0    413
1    348
Name: count, dtype: int64

In [ ]:
train_data_shuffled["target"].value_counts() #not needed

target
0    4342
1    3271
Name: count, dtype: int64

In [ ]:
from tf_keras.callbacks import EarlyStopping, ModelCheckpoint

In [ ]:
model_7 = tf_keras.Sequential([
    sentence_encoder_layer,
    tf_keras.layers.Dense(64, activation = "relu"),
    tf_keras.layers.Dense(1, activation = "sigmoid")
], name = "model_8_USE_10")

model_7.compile(loss = "binary_crossentropy",
                optimizer = tf_keras.optimizers.Adam(),
                metrics = ["accuracy"]
                )
model_7.summary()


Model: "model_8_USE_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 USE (KerasLayer)            (None, 512)               256797824 
                                                                 
 dense_1 (Dense)             (None, 64)                32832     
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 256830721 (979.73 MB)
Trainable params: 32897 (128.50 KB)
Non-trainable params: 256797824 (979.61 MB)
_________________________________________________________________


In [ ]:
model_7_history= model_7.fit(train_sentences_10_percent,
            train_labels_10_percent,
            epochs = 5,
            validation_data=(val_sentences, val_labels),
            )

Epoch 1/5
22/22 [==============================] - 2s 49ms/step - loss: 0.6729 - accuracy: 0.6934 - val_loss: 0.6499 - val_accuracy: 0.7582
Epoch 2/5
22/22 [==============================] - 1s 26ms/step - loss: 0.6100 - accuracy: 0.7869 - val_loss: 0.5912 - val_accuracy: 0.7622
Epoch 3/5
22/22 [==============================] - 1s 23ms/step - loss: 0.5393 - accuracy: 0.7985 - val_loss: 0.5392 - val_accuracy: 0.7661
Epoch 4/5
22/22 [==============================] - 1s 26ms/step - loss: 0.4794 - accuracy: 0.8102 - val_loss: 0.5047 - val_accuracy: 0.7753
Epoch 5/5
22/22 [==============================] - 0s 22ms/step - loss: 0.4399 - accuracy: 0.8234 - val_loss: 0.4832 - val_accuracy: 0.7819


In [ ]:
model_7_preds = tf.squeeze(tf.round(model_7.predict(val_sentences)))
model_7_preds

24/24 [==============================] - 1s 17ms/step


<tf.Tensor: shape=(761,), dtype=float32, numpy=
array([0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1

In [ ]:
model_7_results = calculate_results_advanced(val_labels, model_7_preds)
model_7_results

{'accuracy': 78.18659658344284,
 'precision': 0.7816502524289961,
 'recall': 0.7818659658344284,
 'f1': 0.7817526181847266}

#Saving and loading Trained Model
There are two formats:-
1. HDF5 format (more compatble when not using tensoflow)
2. The SavedModel format (default)

In [ ]:
#HDF5
model_6_results #best one till now

{'accuracy': 80.81471747700394,
 'precision': 0.8070251260667504,
 'recall': 0.8081471747700394,
 'f1': 0.806885296163228}

In [ ]:
model_6.save("model_6.h5")

/usr/local/lib/python3.10/dist-packages/tf_keras/src/engine/training.py:3098: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native TF-Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
loaded_model_6 = tf_keras.models.load_model("model_6.h5",
                                            custom_objects={"KerasLayer": hub.KerasLayer})

In [ ]:
loaded_model_6.evaluate(val_sentences, val_labels)

24/24 [==============================] - 1s 10ms/step - loss: 0.4192 - accuracy: 0.8081


[0.4192354381084442, 0.8081471920013428]

In [ ]:
#saved model format
model_6.save("model_6_SavedModel_format") # no extension needed (stores in a folder)

##Load a trained model

In [ ]:
model_6_SavedModel = tf_keras.models.load_model("model_6_SavedModel_format") #no custom object needed

In [ ]:
model_6_SavedModel.evaluate(val_sentences,val_labels)

24/24 [==============================] - 1s 10ms/step - loss: 0.4192 - accuracy: 0.8081


[0.4192354381084442, 0.8081471920013428]

#To download

In [ ]:
# from google.colab import files
# files.download('model_6_SavedModel_format')

#Finding the most wrong examples
we have to find which of the exaples is our model getting wrong

for example if a sample should have a label 0 but our model predicts a prediction probability of 0.999(really close to 1) and vice versa.


In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/08_model_6_USE_feature_extractor.zip

--2024-09-14 12:09:01--  https://storage.googleapis.com/ztm_tf_course/08_model_6_USE_feature_extractor.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.65.123, 172.217.15.251, 172.217.164.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.65.123|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 960779165 (916M) [application/zip]
Saving to: ‘08_model_6_USE_feature_extractor.zip’

08_model_6_USE_feat 100%[===================>] 916.27M  55.7MB/s    in 22s     

2024-09-14 12:09:23 (40.7 MB/s) - ‘08_model_6_USE_feature_extractor.zip’ saved [960779165/960779165]



In [ ]:
!unzip /content/08_model_6_USE_feature_extractor.zip

Archive:  /content/08_model_6_USE_feature_extractor.zip
   creating: 08_model_6_USE_feature_extractor/
   creating: 08_model_6_USE_feature_extractor/assets/
   creating: 08_model_6_USE_feature_extractor/variables/
  inflating: 08_model_6_USE_feature_extractor/variables/variables.data-00000-of-00001  
  inflating: 08_model_6_USE_feature_extractor/variables/variables.index  
  inflating: 08_model_6_USE_feature_extractor/saved_model.pb  


In [ ]:
model_6_pretrained_model = tf_keras.models.load_model("/content/08_model_6_USE_feature_extractor")
model_6_pretrained_model.evaluate(val_sentences, val_labels)

24/24 [==============================] - 1s 10ms/step - loss: 0.3702 - accuracy: 0.8397


[0.37024760246276855, 0.8396846055984497]

In [ ]:
model_6_pred_prob = model_6_pretrained_model.predict(val_sentences)
model_6_pred = tf.squeeze(tf.round(model_6_pred_prob))
model_6_pred_prob= tf.squeeze(model_6_pred_prob)
model_6_pred[:10]

24/24 [==============================] - 1s 11ms/step


<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 1., 1., 0., 1., 1., 1., 0., 0.], dtype=float32)>

In [ ]:
import pandas as pd
val_df = pd.DataFrame({"text": val_sentences,
                      "target": val_labels, #target = 0:not disaster
                                            #target = 1 disaster
                      "preds": model_6_preds,
                       "pred_probs":model_6_pred_prob})
val_df[:10]

text  target  preds  \
0  Fun with my girls! @ Joe Cools - Durban Main P...       0    0.0   
1  I am that girl on tv that sadly turns her musi...       0    0.0   
2  Dr. Bengston on #wildfire management: ‰ÛÏnumbe...       1    1.0   
3  Families to sue over Legionnaires: More than 4...       1    1.0   
4             @savannahross_4 see tryna ruin my life       0    0.0   
5  Maailiss: Diaporama : sixpenceee: Karymsky Lak...       0    1.0   
6  Purple Heart Vet Finds Jihad Threat on His Car...       0    1.0   
7  US drone bombs Islamic State target in Syria a...       1    1.0   
8  This guy bought my car on Tuesday police knock...       1    0.0   
9  GOP debate drinking game. For anyone looking f...       0    0.0   

   pred_probs  
0    0.075949  
1    0.314643  
2    0.865555  
3    0.965816  
4    0.066610  
5    0.708420  
6    0.679009  
7    0.917659  
8    0.247940  
9    0.058353

In [ ]:
#most wrong values
most_wrong = val_df[val_df["target"] != val_df["preds"]].sort_values("pred_probs", ascending = False)
most_wrong #these are false positives

text  target  preds  \
466  USW: 'The damage from abandoning the deal coul...       0    1.0   
77   Emergency Dispatchers in Boone County in the h...       0    1.0   
601  The first trial in the death of #CecilTheLion ...       0    1.0   
552  San Jose Mercury: Governor Brown allows parole...       0    1.0   
319  if firefighters acted like cops they'd drive a...       0    1.0   
..                                                 ...     ...    ...   
357  Watch These Super Strong Magnets Destroy Every...       1    0.0   
412  Pandemonium use to be my fav cd ?? I had to ge...       1    0.0   
37   OMFG??\nDidnt expect Drag Me Down to be the fi...       1    0.0   
54   @HaydnExists so glad i saved them all at once ...       1    0.0   
263  @lucysforsale funny cause my dumb ass was the ...       1    0.0   

     pred_probs  
466    0.888064  
77     0.876249  
601    0.875304  
552    0.873231  
319    0.867273  
..          ...  
357    0.056312  
412    0.056024  
37     0.055719  
54     0.052181  
263    0.043486  

[146 rows x 4 columns]

In [ ]:
most_wrong.tail() #false negatives

text  target  preds  \
357  Watch These Super Strong Magnets Destroy Every...       1    0.0   
412  Pandemonium use to be my fav cd ?? I had to ge...       1    0.0   
37   OMFG??\nDidnt expect Drag Me Down to be the fi...       1    0.0   
54   @HaydnExists so glad i saved them all at once ...       1    0.0   
263  @lucysforsale funny cause my dumb ass was the ...       1    0.0   

     pred_probs  
357    0.056312  
412    0.056024  
37     0.055719  
54     0.052181  
263    0.043486

##check false positive(model predicted 1 when should have been 0)

In [ ]:
for row in most_wrong[:10].itertuples():
  _, text,target, preds, pred_prob = row
  print(f"target: {target}, preds: {preds}, pred_prob: {pred_prob}")
  print(f"text:\n{text}\n")
  print("-------\n")

target: 0, preds: 1.0, pred_prob: 0.8880637288093567
text:
USW: 'The damage from abandoning the deal could well create a new level of uncertainty...economic upheaval &amp; military unrest'

-------

target: 0, preds: 1.0, pred_prob: 0.8762493133544922
text:
Emergency Dispatchers in Boone County in the hot seat http://t.co/5fHkxtrhYU

-------

target: 0, preds: 1.0, pred_prob: 0.8753042817115784
text:
The first trial in the death of #CecilTheLion was just postponed http://t.co/fnmJE8GF7m http://t.co/nYe8ae2ifr

-------

target: 0, preds: 1.0, pred_prob: 0.8732314109802246
text:
San Jose Mercury: Governor Brown allows parole for California school bus hijacker  http://t.co/GpCeCp9kHv

-------

target: 0, preds: 1.0, pred_prob: 0.8672730922698975
text:
if firefighters acted like cops they'd drive around shooting a flamethrower at burning buildings

-------

target: 0, preds: 1.0, pred_prob: 0.8659653067588806
text:
The government is concerned about the population explosion and the populati

##check false negative(model predicted 0 when should have been 1)

In [ ]:
for row in most_wrong[:-10].itertuples():
  _,text,target,preds,pred_prob = row
  print(f"target: {target}, preds: {preds}, pred_prob: {pred_prob}")
  print(f"text:\n{text}\n")
  print("-------\n")

target: 0, preds: 1.0, pred_prob: 0.8880637288093567
text:
USW: 'The damage from abandoning the deal could well create a new level of uncertainty...economic upheaval &amp; military unrest'

-------

target: 0, preds: 1.0, pred_prob: 0.8762493133544922
text:
Emergency Dispatchers in Boone County in the hot seat http://t.co/5fHkxtrhYU

-------

target: 0, preds: 1.0, pred_prob: 0.8753042817115784
text:
The first trial in the death of #CecilTheLion was just postponed http://t.co/fnmJE8GF7m http://t.co/nYe8ae2ifr

-------

target: 0, preds: 1.0, pred_prob: 0.8732314109802246
text:
San Jose Mercury: Governor Brown allows parole for California school bus hijacker  http://t.co/GpCeCp9kHv

-------

target: 0, preds: 1.0, pred_prob: 0.8672730922698975
text:
if firefighters acted like cops they'd drive around shooting a flamethrower at burning buildings

-------

target: 0, preds: 1.0, pred_prob: 0.8659653067588806
text:
The government is concerned about the population explosion and the populati

In [ ]:
test_data

id keyword location  \
0         0     NaN      NaN   
1         2     NaN      NaN   
2         3     NaN      NaN   
3         9     NaN      NaN   
4        11     NaN      NaN   
...     ...     ...      ...   
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
0                    Just happened a terrible car crash  
1     Heard about #earthquake is different cities, s...  
2     there is a forest fire at spot pond, geese are...  
3              Apocalypse lighting. #Spokane #wildfires  
4         Typhoon Soudelor kills 28 in China and Taiwan  
...                                                 ...  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather Outlook (HWO) htt...  
3262  #CityofCalgary has activated its Municipal Eme...  

[3263 rows x 4 columns]

In [ ]:
test_sentences = test_data["text"].to_list()
test_samples = random.sample(test_sentences, 10)#pick 10 sentences
for test_sample in test_samples:
  pred_probs = tf.squeeze(model_6_pretrained_model.predict([test_sample]))
  pred= tf.round(pred_probs)
  print(f"pred: {int(pred)}, probs: {pred_probs}")
  print(f"text_sample: \n{text_sample}\n")
  print("........\n")

1/1 [==============================] - 0s 44ms/step
pred: 1, probs: 0.9628240466117859
text_sample: 
[[[ 0.02239764 -0.01245258 -0.04062137 ... -0.04477341 -0.05737216
   -0.00197347]
  [ 0.06805478 -0.03506765 -0.0541717  ...  0.03582341 -0.09578142
    0.02340902]
  [-0.05957595 -0.02578719 -0.05945874 ... -0.05576746 -0.05607562
    0.00593478]
  ...
  [-0.02733136 -0.00046978 -0.03324375 ... -0.01999495 -0.03667902
   -0.05314578]
  [-0.02733136 -0.00046978 -0.03324375 ... -0.01999495 -0.03667902
   -0.05314578]
  [-0.02733136 -0.00046978 -0.03324375 ... -0.01999495 -0.03667902
   -0.05314578]]]

........

1/1 [==============================] - 0s 44ms/step
pred: 0, probs: 0.4614371359348297
text_sample: 
[[[ 0.02239764 -0.01245258 -0.04062137 ... -0.04477341 -0.05737216
   -0.00197347]
  [ 0.06805478 -0.03506765 -0.0541717  ...  0.03582341 -0.09578142
    0.02340902]
  [-0.05957595 -0.02578719 -0.05945874 ... -0.05576746 -0.05607562
    0.00593478]
  ...
  [-0.02733136 -0.00046978

##prediction on my name

In [ ]:
pred_probs = model_6_pretrained_model.predict(["My name is ayush"])
pred= tf.round(pred_probs)
int(pred)

1/1 [==============================] - 0s 146ms/step


0

#speed/score trade off


In [ ]:
model_6_results

{'accuracy': 80.81471747700394,
 'precision': 0.8070251260667504,
 'recall': 0.8081471747700394,
 'f1': 0.806885296163228}

In [ ]:
baseline_results

{'accuracy': 79.89487516425756,
 'precision': 0.8095562735335368,
 'recall': 0.7989487516425755,
 'f1': 0.7905183694503822}

###pred_timer() to measure time the model makes

In [ ]:
import time
def pred_timer(model,sample):
  start_time = time.perf_counter() #start time
  model.predict(sample)
  end_time= time.perf_counter() #end_time
  total_time= end_time-start_time
  time_per_pred= total_time/len(sample)
  return total_time, time_per_pred


In [ ]:
#calculate tf hub sentence encoder
model_6_total_pred_time, model_6_time_per_pred = pred_timer(model_6_pretrained_model,val_sentences)
model_6_total_pred_time, model_6_time_per_pred

24/24 [==============================] - 1s 24ms/step


(0.83129841400023, 0.0010923763653091065)

In [ ]:
#calculate baseline time
baseline_total_time, baseline_time_per_pred = pred_timer(model_0, val_sentences)
baseline_total_time, baseline_time_per_pred

(0.047455799999625015, 6.235978974983576e-05)